import Head from "next/head";
import { useRouter } from "next/router";
import { FormEventHandler, useEffect, useState } from "react";
import SimplePeer from "simple-peer";

export default function Home() {
  const { query, pathname } = useRouter();
  const [peer, setPeer] = useState<SimplePeer.Instance | null>();
  const [offer, setOffer] = useState("");
  const [message, setMessage] = useState("");
  const [url, setUrl] = useState("");

  useEffect(() => {
    const newPeer = new SimplePeer({
      initiator: query.init === "true",
      trickle: false,
    });

    newPeer.on("signal", (data: any) => {
      const offer = JSON.stringify(data);

      setUrl(window.location.origin + `?offer=${offer}`);
    });

    newPeer.on("connect", () => {
      console.log("CONNECT");
      newPeer.send("whatever" + Math.random());
    });

    newPeer.on("data", (data) => {
      console.log("is this data ?");
      setMessage(String(data.toString()));
    });

    setPeer(newPeer);
  }, [query.init]);

  useEffect(() => {
    if (query.offer && peer) {
      peer.signal(query.offer as string);
    }
  }, [peer, query.offer]);

  return (
    <>
      <Head>
        <title>Math Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {message}
        URL: {url}
      </main>
    </>
  );
}
